 services:
  emisoft.cleanarchitecture.web:
    image: ${DOCKER_REGISTRY-}emisoftcleanarchitectureweb
    build:
      context: .
      dockerfile: src/Presentation/EmiSoft.CleanArchitecture.Web/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  #rabbitmq:
  #  image: rabbitmq:3-management

  #elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  #kibana:
  #  image: docker.elastic.co/kibana/kibana:7.9.2

 volumes:
  mssql_data:
  #elasticsearch_data:
  #rabbitmq_data:

 networks:
  edmsnetwork:
    driver: bridge