version: '3.4'

services:
  emisoft.cleanarchitecture.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - mssql
      #- rabbitmq
    networks:
      - emisoftnetwork

  mssql:
    container_name: mssql
    user: root
    environment:
      SA_PASSWORD: "P@ssword"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - mssql_data:/var/opt/mssql/data
    networks:
    - emisoftnetwork

  #rabbitmq:
  #  container_name: rabbitmq
  #  environment:
  #    RABBITMQ_DEFAULT_USER: "rabbitmq"
  #    RABBITMQ_DEFAULT_PASS: "rabbitmq"
  #    RABBITMQ_DEFAULT_VHOST: "/"
  #  ports:
  #    - "15672:15672"
  #    - "5672:5672"
  #  volumes:
  #    - rabbitmq_data:/var/lib/rabbitmq  
  #  networks:      
  #    - emisoftnetwork


  #elasticsearch:
  #  container_name: elasticsearch
  #  environment:
  #    - xpack.monitoring.enabled=true
  #    - xpack.watcher.enabled=false
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    - discovery.type=single-node
  #    - node.name=elasticsearch
  #    - cluster.name=elasticsearch-docker-cluster
  #  ports:
  #    - "9200:9200"
  #  volumes:
  #    - elasticsearch_data:/usr/share/elasticsearch/data   
  #  networks:      
  #    - emisoftnetwork

  #kibana:
  #  container_name: kibana
  #  environment:        
  #    - ELASTICSEARCH_URL=http://elasticsearch:9200
  #  depends_on:
  #    - elasticsearch
  #  ports:
  #    - "5601:5601"  
  #  networks:      
  #    - emisoftnetwork